### ISSUE TITLE
Kasutajate e-mail aadress

### ISSUE THREAD

**Issue by genxlee** [raitnigol/activedirectory#1]
Loodud kasutajatel peab olema ettevõtte domeeniga meiliaaddress (mukri.sise).
https://github.com/raitnigol/activedirectory/blob/b693f63f6fa44657e77de75ca2917bad278f3ffc/activedirectory_script.ps1#L82

**Comment by raitnigol** [comment]
> Loodud kasutajatel peab olema ettevõtte domeeniga meiliaaddress (mukri.sise).
> https://github.com/raitnigol/activedirectory/blob/b693f63f6fa44657e77de75ca2917bad278f3ffc/activedirectory_script.ps1#L82

Tegin väikese muudatuse ning nüüd peaks see olema korrektne.
https://github.com/raitnigol/activedirectory/blob/master/activedirectory_script.ps1#L81

> $email = $("$Username@$domain").ToLower()
